---
  - name: Setup PHP
    apt: name={{item}} state=latest
    with_items:
      - php5
      - php5-cli
      - php5-mysql
      - php5-gd
      - php-pear
      - php5-mcrypt
      - php5-memcache
      - php5-curl
      - php5-dev
    notify: restart apache2

  - name: Install make
    apt: pkg=make state=latest

  - name: Install xdebug
    shell: pecl upgrade xdebug

  - name: Configure xdebug
    template:
      src=templates/xdebug.ini.j2
      dest=/etc/php5/mods-available/xdebug.ini
      owner=root group=root mode=0644

  - name: Configure PHP development
    template:
      src=templates/dev.ini.j2
      dest=/etc/php5/mods-available/dev.ini
      owner=root group=root mode=0644

  - name: Activate WK dev
    shell: php5enmod {{ item }}
    with_items:
      - xdebug
      - dev
