<?php

function semantic_panels_eq_height_form_alter(&$form, &$form_state, $form_id){

  if($form_id == 'panels_edit_style_settings_form' && $form_state['type'] == 'region' && $form_state['style']['name'] == 'semantic_panels'){

    $settings = $form_state['conf'];

    $form['settings']['equal_height']['active'] = array(
      '#type' => 'checkbox',
      '#title' => t('Have all panes be equal height (per row)'),
      '#description' => t('If active all panes in this region will be set to the same height (per row)'),
      '#default_value' => $settings['equal_height']['active'],
    );

    //Add any weight to submit button to make it be last
    $form['submit']['#weight'] = $form['submit']['#weight'] ? $form['submit']['#weight'] : 1;
  }

  return $form;
}

function semantic_panels_eq_height_semantic_panels_region_alter(&$output, $vars){

  $settings = $vars['settings'];

  if(!empty($settings['equal_height']) && $settings['equal_height']['active'] === 1){

    drupal_add_js(libraries_get_path('jquery.equalblocks') . '/jquery.equalblocks.js');
    drupal_add_js(drupal_get_path('module', 'semantic_panels_eq_height') . '/js/semantic-panels-eq-height.js');

    $output = '<div class="equalBlocks-wrapper clearfix">' . $output . '</div>';
  }
};