<?php

/**
* Implementation of hook_form_alter()
*/
//function sa_custom_form_alter(&$form, &$form_state, $form_id){
//  return $form;
//}


//function sa_custom_views_pre_render(&$view){
//  //dpm($view);
//}


function sa_custom_quicktabs_alter($quicktabs, $op) {

 // Hide quicktabs tabs if user is not allowed to reorder them with draggable views.
//
// TODO: We need to fix a template.php function to hide the markup for this also
 if (isset($quicktabs->machine_name) == 'image_slide'){
   if(!user_access('Allow Reordering')) {
      $i = 0;
      $slide_tabs = $quicktabs->tabs;
      foreach($slide_tabs AS $i => $value){
        unset($quicktabs->tabs[$i]['title']);
      }
    }
  }
}